[package]
name = "aoc-2020-10"
version = "0.1.0"
authors = ["Markus Dittmann <dmarku@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
